# Attention! ALL paths must be relative to the 'config.yml' file!

dataset_name: genia
data_path: data/{dataset_name}/genia_ner.py
num_proc: 4
nested: True  # whether the entities are nested

# process config
tokens_field: tokens  # the field name of the tokens, please make sure the field name is consistent with the data
ner_tags_field: ner_tags  # the field name of the NER tag, please make sure the field name is consistent with the data
batch_size: 4096 # batch size for data processing
split: test  # train, dev, test
shuffle: True  # whether to shuffle the data
preprocessed_dir: data/{dataset_name}/preprocess  # the directory to store the preprocessed data
continue: True  # whether to continue to use the data last time
continue_dir: data/{dataset_name}/continue  # the directory to store the continued data to be annotated

support_set: True  # whether to sample support set
k_shot:  # the number of examples for each label in the training set
  - 7
  - 5
  - 3
  - 1
sample_split: train  # the dataset split you want to sample support set from.
ss_cache_dir: data/{dataset_name}/support_set  # the directory to store the support set cache