# Attention! ALL paths must be relative to the 'config.yml' file!
dataset_name: ontonotes5_en
data_path: data/{dataset_name}/ontonotes5_en.py
# the name of the configuration to be loaded,
# see https://huggingface.co/docs/datasets/package_reference/loading_methods#datasets.load_dataset.name
cfg_name: ~
num_proc: 4
nested: False  # whether the entities are nested
language: en  # language

# process config
tokens_field: tokens  # the field name of the tokens, please make sure the field name is consistent with the data
ner_tags_field: tags  # the field name of the NER tag, please make sure the field name is consistent with the data
batch_size: 4096 # batch size for data processing
split: test  # train, dev, test
shuffle: True  # whether to shuffle the data
preprocessed_dir: data/{dataset_name}/preprocess  # the directory to store the preprocessed data
continue: True  # whether to continue to use the data last time
continue_dir: data/{dataset_name}/continue  # the directory to store the continued data to be annotated

support_set: True  # whether to sample support set
k_shot:  # the number of examples for each label in the training set
  - 7
  - 5
  - 3
  - 1
sample_split: train  # the dataset split you want to sample support set from.
ss_cache_dir: data/{dataset_name}/support_set  # the directory to store the support set cache